name: Christian Stigen Larsen
author: Christian Stigen Larsen
markdown: redcarpet
highlighter: true
permalink: /post/:title/
encoding: utf-8
timezone: Norway/Oslo

# File lists
include: [.htaccess]
exclude: [TODO, Makefile, README.md, Gemfile, draft.sh]

# additional settings for RSS
copyright: "&copy; 1996-2016 Christian Stigen Larsen.<br/>Verbatim copying and redistribution of content from this site is permitted provided this notice is preserved.<br/>"
description: "Personal homepage with posts mainly on programming"
url: https://csl.name

# Various settings
email: "csl@csl.name"
twitter: "https://twitter.com/cstigenlarsen"
github: "https://github.com/cslarsen"
linkedin: "http://no.linkedin.com/pub/christian-s-larsen/0/935/b61"
facebook: "https://www.facebook.com/christianstigen"
googleplus: "https://plus.google.com/112152592957527288979/posts"
stackoverflow: "http://stackoverflow.com/users/21028/csl"
speakerdeck: "http://speakerdeck.com/csl"

# Google adsense
adsense_tracking_id: UA-831752-4

# Disqus
disqus_user: christianstigenlarsen

# Fonts
google_font:
  name: Raleway
  weights: "300,400,500"
  ligatures: normal
