name: Christian Stigen Larsen
author: Christian Stigen Larsen
markdown: redcarpet
highlighter: true
permalink: /post/:title/
encoding: utf-8
timezone: Norway/Oslo
redirect_to_https: true

# File lists
include: [.htaccess]
exclude: [TODO, Makefile, README.md, Gemfile, draft.sh]

# additional settings for RSS
copyright: "&copy; 1996-2017 Christian Stigen Larsen.<br/>Verbatim copying and redistribution of content from this site is permitted provided this notice is preserved.<br/><a href='https://github.com/cslarsen/csl.name'>Site source</a>."
description: "Personal homepage with posts mainly on programming"
url: https://csl.name
baseurl: ""

# Various settings
email: "csl@csl.name"
twitter: "https://twitter.com/cstigenlarsen"
github: "https://github.com/cslarsen"
linkedin: "https://no.linkedin.com/in/christian-stigen-larsen-b61935"
facebook: "https://www.facebook.com/christianstigen"
googleplus: "https://plus.google.com/112152592957527288979/posts"
stackoverflow: "http://stackoverflow.com/users/21028/csl"
speakerdeck: "http://speakerdeck.com/csl"

# Google adsense
adsense_tracking_id: UA-831752-4
# Disable Google adsense because Google page speed drops way down when I use it
adsense: false

# Disqus
disqus_user: christianstigenlarsen

# Fonts
google_font:
  name: Raleway
  weights: "300,400,500"
  ligatures: normal
