name: Christian Stigen Larsen
author: Christian Stigen Larsen
markdown: redcarpet
highlighter: true
permalink: /post/:title/

# File lists
include: [.htaccess]
exclude: [TODO, Makefile, README.md, Gemfile]

# additional settings for RSS
copyright: "Copyright &copy; 1997&mdash;2013 Christian Stigen Larsen.<br/>Verbatim copying and redistribution of content from this site is permitted provided this notice is preserved.<br/>"
description: "Personal homepage with posts mainly on programming"
url: http://foobar.nfshost.com

# Various settings
email: "csl@csl.name"
twitter: "https://twitter.com/cstigenlarsen"
github: "https://github.com/cslarsen"
linkedin: "http://no.linkedin.com/pub/christian-s-larsen/0/935/b61"
facebook: "https://www.facebook.com/christianstigen"
googleplus: "https://plus.google.com/112152592957527288979/posts"
stackoverflow: "http://stackoverflow.com/users/21028/csl"

# Google adsense
adsense_tracking_id: UA-831752-4

# Disqus
disqus_user: christianstigenlarsen

# Fonts
google_font:
  name: Raleway
  weights: "200,400,600,800,900"
  ligatures: normal
